apiVersion: v1
kind: Deployment
metadata:
  name: depart-docker-k8s-deployment
  labels:
    app: depart-docker-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depart-docker-k8
  template:
    metadata:
      labels:
        app: depart-docker-k8
    spec:
      containers:
      - name: depart-docker-k8
      image: nickchase/rss-php-nginx:v1
      ports:
        - containerPort: 9001